modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20Breeze%20Spawn"
logoFile="icon.png"

[[mods]]
modId="breezespawn"
version="1.1"
displayName="Breeze Spawn"
displayURL="https://curseforge.com/minecraft/mc-mods/breeze-spawn"
authors="Rick South"
description='''Adds a chance for breezes to spawn naturally everywhere in place of a blaze.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Alister, Andrean Olgo, aternosorg, Cherriesaurus, Michael W. S., Nahuel Fernandez, Shana Gitnick, Tyler Behl   

If you would like to contribute too, check out https://serilum.com/donate. Appreciate it! <3   
'''

[[dependencies.breezespawn]]
    modId="collective"
    type="required"
    versionRange="[7.78,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.breezespawn]]
    modId="minecraft"
    type="required"
    versionRange="[1.21]"
    ordering="NONE"
    side="BOTH"

[[mixins]]
    config = "breezespawn.mixins.json"